on: 
  push:
    branches: [ master ]
    paths-ignore:
    - '**/README.md'
    - '**/docs/**'
name: Build and release on push
jobs:
  build-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Choco Install llvm  
        uses: crazy-max/ghaction-chocolatey@v2
        with: 
          args: install llvm -y
      - name: Compile binaries
        run: '&$Env:programfiles\LLVM\bin\clang++.exe ./src/main.cpp -std=c++17 -O3 --output EasyBonsai3-Win.exe'
      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./EasyBonsai3-Win.exe
          release: EasyBonsai3
          prerelease: false
  build-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'true'
      - name: Install Clang
        run: sudo apt-get update -y && sudo apt-get install -yq clang
      - name: Compile binaries
        run: clang++ ./src/main.cpp -std=c++17 -O3 -o EasyBonsai3-Linux
      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./EasyBonsai3-Linux
          release: EasyBonsai3
          prerelease: false
  build-JS:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v8
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Compile binaries
        run: em++ ./src/main.cpp -std=c++17 -O3 -o EasyBonsai3.js -D BONSAI_WEB --bind -s USE_ES6_IMPORT_META=1 -s ENVIRONMENT="web"
      - name: Update Release 1
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./EasyBonsai3.js
          release: 'EasyBonsai3 Web'
          prerelease: false
      - name: Update Release 2
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./EasyBonsai3.wasm
          release: 'EasyBonsai3 Web'
          prerelease: false