name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Build and Deploy
      uses: rreichel3/vuepress-github-actions-deploy@v3.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: src/.vuepress/dist/
        BUILD_SCRIPT: cd docs && yarn && yarn build